### ISSUE TITLE
Array Declare issue

### ISSUE THREAD

**Issue by Hobo2k** [Jorgen-VikingGod/ESP8266-MFRC522#1]
Hi,

With Arduino version 1.6.6 I get this error:

exit status 1
'dump_byte_array' was not declared in this scope

How should I declare this variable?

Thanks

**Comment by Jorgen-VikingGod** [comment]
it is not a variable it is a method to print out the uid to Serial.
Perhaps you have to move the method on top, to have it in content.
Don't know, why it isn't running on 1.6.6
I will try this later on my setup.
But there is no magic - simple method call

**Comment by chinmoyrick** [comment]
All code of this code is working . that's true there is no magic .there is some header file library file and a  proper sketch. those code are working properly . you have to check it one by one. to avoid those type of error create a new sketch and drop code one by one and copy all library file &  header file also.

**Comment by Hobo2k** [comment]
The same saved code is working on 1.6.4 and 1.6.5 but not at 1.6.6 on my pc.
I'm using 1.6.5 at the moment.

**Comment by Jorgen-VikingGod** [comment]
Ok I found an open issue about 1.6.6
https://github.com/esp8266/Arduino/issues/1194

So you have to declare the method 'dump_byte_array' before the method (here 'loop') where you all it.
This is just a workaround until they fix this issue in the arduino ide.
